var a = 
[
  {
    "no": 1,
    "group": "I",
    "is": false,
    "kanji": "会います",
    "kanji2": "",
    "note": "ともだちに~",
    "vi": "gặp [bạn]",
    "img": "会います.jpg",
    "furigana": "<ruby><rb>会</rb><rp>(</rp><rt>あ</rt><rp>)</rp></ruby>います",
    "en": "to meet, to encounter, to see, to have an accident, to have a bad experience",
    "masu": " あいます"
  },
  {
    "no": 2,
    "group": "I",
    "is": false,
    "kanji": "遊びます",
    "kanji2": "",
    "note": "",
    "vi": "chơi",
    "img": "遊びます.jpg",
    "furigana": "<ruby><rb>遊</rb><rp>(</rp><rt>あそ</rt><rp>)</rp></ruby>びます",
    "en": "to play, to enjoy oneself, to have a good time, to mess about (with alcohol, gambling, philandery, etc.), to be idle, to do nothing, to be unused, to go to (for pleasure or for study), to intentionally throw a ball to lower the batter's concentration",
    "masu": "あそびます"
  },
  {
    "no": 3,
    "group": "I",
    "is": false,
    "kanji": "洗います",
    "kanji2": "",
    "note": "",
    "vi": "rửa",
    "img": "洗います.png",
    "furigana": "<ruby><rb>洗</rb><rp>(</rp><rt>あら</rt><rp>)</rp></ruby>います",
    "en": "to wash, to investigate",
    "masu": "あらいます"
  },
  {
    "no": 4,
    "group": "I",
    "is": false,
    "kanji": "あります",
    "kanji2": "",
    "note": "",
    "vi": "có (sở hữu)",
    "img": "あります.jpg",
    "furigana": "あります",
    "en": "to be (usu. of inanimate objects), to exist, to live, to have, to be located, to be equipped with, to happen, to come about",
    "masu": "あります"
  },
  {
    "no": 5,
    "group": "I",
    "is": false,
    "kanji": "あります",
    "kanji2": "",
    "note": "",
    "vi": "ở (tồn tại, dùng cho đồ vật)",
    "img": "あります2.jpg",
    "furigana": "あります",
    "en": "to be (usu. of inanimate objects), to exist, to live, to have, to be located, to be equipped with, to happen, to come about",
    "masu": "あります"
  },
  {
    "no": 6,
    "group": "I",
    "is": false,
    "kanji": "あります",
    "kanji2": "",
    "note": "おまつりが~",
    "vi": "[lễ hội] được tổ chức, diễn ra",
    "img": "おまつりがあります.jpg",
    "furigana": "あります",
    "en": "to be (usu. of inanimate objects), to exist, to live, to have, to be located, to be equipped with, to happen, to come about",
    "masu": "あります"
  },
  {
    "no": 7,
    "group": "I",
    "is": false,
    "kanji": "歩きます",
    "kanji2": "",
    "note": "",
    "vi": "đi bộ",
    "img": "歩きます.png",
    "furigana": "<ruby><rb>歩</rb><rp>(</rp><rt>ある</rt><rp>)</rp></ruby>きます",
    "en": "to walk",
    "masu": "あるきます"
  },
  {
    "no": 8,
    "group": "I",
    "is": false,
    "kanji": "言います",
    "kanji2": "",
    "note": "",
    "vi": "nói",
    "img": "言います.jpg",
    "furigana": "<ruby><rb>言</rb><rp>(</rp><rt>い</rt><rp>)</rp></ruby>います",
    "en": "to say, to utter, to declare, to name, to call, to go (e.g. &quot;the alarm went ping&quot;), to make a noise",
    "masu": "いいます"
  },
  {
    "no": 9,
    "group": "I",
    "is": false,
    "kanji": "行きます",
    "kanji2": "",
    "note": "",
    "vi": "đi",
    "img": "行きます.jpg",
    "furigana": "<ruby><rb>行</rb><rp>(</rp><rt>い</rt><rp>)</rp></ruby>きます",
    "en": "to go, to move (in a direction or towards a specific location), to head (towards), to be transported (towards), to reach, to proceed, to take place, to pass through, to come and go, to walk, to die, to pass away, to do (in a specific way), to stream, to flow, to continue, to have an orgasm, to come,...",
    "masu": "いきます"
  },
  {
    "no": 10,
    "group": "I",
    "is": false,
    "kanji": "急ぎます",
    "kanji2": "",
    "note": "",
    "vi": "vội, gấp",
    "img": "急ぎます.png",
    "furigana": "<ruby><rb>急</rb><rp>(</rp><rt>いそ</rt><rp>)</rp></ruby>ぎます",
    "en": "to hurry, to rush, to hasten, to make something happen sooner",
    "masu": "いそぎます"
  },
  {
    "no": 11,
    "group": "I",
    "is": false,
    "kanji": "要ります",
    "kanji2": "",
    "note": "ビザが~",
    "vi": "cần [thị thực/visa]",
    "img": "ビザが要ります.jpg",
    "furigana": "<ruby><rb>要</rb><rp>(</rp><rt>い</rt><rp>)</rp></ruby>ります",
    "en": "to need, to want",
    "masu": "いります"
  },
  {
    "no": 12,
    "group": "I",
    "is": false,
    "kanji": "動きます",
    "kanji2": "",
    "note": "動くクマ",
    "vi": "chuyển động, chạy",
    "img": "動くクマ.png",
    "furigana": "<ruby><rb>動</rb><rp>(</rp><rt>うご</rt><rp>)</rp></ruby>きます",
    "en": "to move, to stir, to shift, to shake, to swing, to operate, to run, to go, to work, to be touched, to be influenced, to change, to vary, to fluctuate, to waver, certain, factual, to be transferred",
    "masu": "うごきます"
  },
  {
    "no": 13,
    "group": "I",
    "is": false,
    "kanji": "歌います",
    "kanji2": "",
    "note": "",
    "vi": "hát",
    "img": "歌います.jpg",
    "furigana": "<ruby><rb>歌</rb><rp>(</rp><rt>うた</rt><rp>)</rp></ruby>います",
    "en": "to sing, to sing (one's praises in a poem, etc.), to compose a poem, to recite a poem",
    "masu": "うたいます"
  },
  {
    "no": 14,
    "group": "I",
    "is": false,
    "kanji": "売ります",
    "kanji2": "",
    "note": "",
    "vi": "bán",
    "img": "売ります.jpg",
    "furigana": "<ruby><rb>売</rb><rp>(</rp><rt>う</rt><rp>)</rp></ruby>ります",
    "en": "to sell",
    "masu": "うります"
  },
  {
    "no": 15,
    "group": "I",
    "is": false,
    "kanji": "置きます",
    "kanji2": "",
    "note": "",
    "vi": "đặt, để",
    "img": "置きます.jpg",
    "furigana": "<ruby><rb>置</rb><rp>(</rp><rt>お</rt><rp>)</rp></ruby>きます",
    "en": "to put, to place, to leave (behind), to establish (an organization, a facility, a position, etc.), to set up, to appoint (someone to a certain position), to hire, to employ, to place (one's trust, one's faith, etc), to bear (in mind etc), to put down a tool (e.g. a pen) hence stopping what one is do...",
    "masu": "おきます"
  },
  {
    "no": 16,
    "group": "I",
    "is": false,
    "kanji": "送ります",
    "kanji2": "",
    "note": "",
    "vi": "gửi",
    "img": "送ります.jpg",
    "furigana": "<ruby><rb>送</rb><rp>(</rp><rt>おく</rt><rp>)</rp></ruby>ります",
    "en": "to send (a thing), to dispatch, to despatch, to transmit, to take or escort (a person somewhere), to see off (a person), to bid farewell (to the departed), to bury, to spend (time), to live one's life, to pass (down the line), to affix okurigana",
    "masu": "おくります"
  },
  {
    "no": 17,
    "group": "I",
    "is": false,
    "kanji": "送ります",
    "kanji2": "",
    "note": "ひとを~",
    "vi": "tiễn [một ai đó]",
    "img": "ひとを送ります.jpg",
    "furigana": "<ruby><rb>送</rb><rp>(</rp><rt>おく</rt><rp>)</rp></ruby>ります",
    "en": "to send (a thing), to dispatch, to despatch, to transmit, to take or escort (a person somewhere), to see off (a person), to bid farewell (to the departed), to bury, to spend (time), to live one's life, to pass (down the line), to affix okurigana",
    "masu": "おくります"
  },
  {
    "no": 18,
    "group": "I",
    "is": false,
    "kanji": "押します",
    "kanji2": "",
    "note": "",
    "vi": "bấm, ấn",
    "img": "押します.jpg",
    "furigana": "<ruby><rb>押</rb><rp>(</rp><rt>お</rt><rp>)</rp></ruby>します",
    "en": "to push, to press, to apply pressure from above, to press down, to stamp (i.e. a passport), to apply a seal, to affix (e.g. gold leaf), to press (someone for something), to urge, to compel, to influence, to overwhelm, to overpower, to repress, to push (events along), to advance (a plan), to do in sp...",
    "masu": "おします"
  },
  {
    "no": 19,
    "group": "I",
    "is": false,
    "kanji": "思い出します",
    "kanji2": "",
    "note": "",
    "vi": "nhớ lại, hồi tưởng lại",
    "img": "思い出します.jpg",
    "furigana": "<ruby><rb>思</rb><rp>(</rp><rt>おも</rt><rp>)</rp></ruby>い<ruby><rb>出</rb><rp>(</rp><rt>だ</rt><rp>)</rp></ruby>します",
    "en": "to recall, to remember, to recollect",
    "masu": "おもいだします"
  },
  {
    "no": 20,
    "group": "I",
    "is": false,
    "kanji": "思います",
    "kanji2": "",
    "note": "",
    "vi": "nghĩ",
    "img": "思います.jpg",
    "furigana": "<ruby><rb>思</rb><rp>(</rp><rt>おも</rt><rp>)</rp></ruby>います",
    "en": "to think, to consider, to believe, to think (of doing), to plan (to do), to judge, to assess, to regard, to imagine, to suppose, to dream, to expect, to look forward to, to feel, to desire, to want, to recall, to remember",
    "masu": "おもいます"
  },
  {
    "no": 21,
    "group": "I",
    "is": false,
    "kanji": "泳ぎます",
    "kanji2": "",
    "note": "",
    "vi": "bơi",
    "img": "泳ぎます.jpg",
    "furigana": "<ruby><rb>泳</rb><rp>(</rp><rt>およ</rt><rp>)</rp></ruby>ぎます",
    "en": "to swim",
    "masu": "およぎます"
  },
  {
    "no": 22,
    "group": "I",
    "is": false,
    "kanji": "下ろします",
    "kanji2": "",
    "note": "おかねを~",
    "vi": "rút [tiền]",
    "img": "おかねを下ろします.jpg",
    "furigana": "<ruby><rb>下</rb><rp>(</rp><rt>お</rt><rp>)</rp></ruby>ろします",
    "en": "to take down (e.g. flag), to launch (e.g. boat), to drop, to lower (e.g. ladder), to let (a person) off, to unload, to discharge, to drop off (a passenger from a vehicle), to let (a person) off, to withdraw money from an account, to wear (clothing) for the first time, to fillet (e.g. a fish)",
    "masu": "おろします"
  },
  {
    "no": 23,
    "group": "I",
    "is": false,
    "kanji": "終わります",
    "kanji2": "",
    "note": "",
    "vi": "hết, kết thúc, xong",
    "img": "終わります.jpg",
    "furigana": "<ruby><rb>終</rb><rp>(</rp><rt>お</rt><rp>)</rp></ruby>わります",
    "en": "to finish, to end, to close",
    "masu": "おわります"
  },
  {
    "no": 24,
    "group": "I",
    "is": false,
    "kanji": "買います",
    "kanji2": "",
    "note": "",
    "vi": "mua",
    "img": "買います.jpg",
    "furigana": "<ruby><rb>買</rb><rp>(</rp><rt>か</rt><rp>)</rp></ruby>います",
    "en": "to buy, to purchase, to value, to have a high opinion, to stir, to provoke",
    "masu": "かいます"
  },
  {
    "no": 25,
    "group": "I",
    "is": false,
    "kanji": "返します",
    "kanji2": "",
    "note": "",
    "vi": "trả lại",
    "img": "返します.jpg",
    "furigana": "<ruby><rb>返</rb><rp>(</rp><rt>かえ</rt><rp>)</rp></ruby>します",
    "en": "to return (something), to restore, to put back, to turn over, to turn upside down, to overturn, to pay back, to retaliate, to reciprocate, to repeat ..., to do ... back",
    "masu": "かえします"
  },
  {
    "no": 26,
    "group": "I",
    "is": false,
    "kanji": "帰ります",
    "kanji2": "",
    "note": "",
    "vi": "về",
    "img": "帰ります.jpg",
    "furigana": "<ruby><rb>帰</rb><rp>(</rp><rt>かえ</rt><rp>)</rp></ruby>ります",
    "en": "to return, to come home, to go home, to go back, to leave, to get home, to get to home plate",
    "masu": "かえります"
  },
  {
    "no": 27,
    "group": "I",
    "is": false,
    "kanji": "かかります",
    "kanji2": "",
    "note": "",
    "vi": "mất, tốn (thời gian, tiền bạc)",
    "img": "かかります.jpg",
    "furigana": "かかります",
    "en": "to suffer from",
    "masu": "かかります"
  },
  {
    "no": 28,
    "group": "I",
    "is": false,
    "kanji": "書きます",
    "kanji2": "",
    "note": "",
    "vi": "viết, vẽ",
    "img": "書きます.jpg",
    "furigana": "<ruby><rb>書</rb><rp>(</rp><rt>か</rt><rp>)</rp></ruby>きます",
    "en": "to write, to compose, to pen, to draw, to paint",
    "masu": "かきます"
  },
  {
    "no": 29,
    "group": "I",
    "is": false,
    "kanji": "貸します",
    "kanji2": "",
    "note": "",
    "vi": "cho mượn, cho vay",
    "img": "貸します.jpg",
    "furigana": "<ruby><rb>貸</rb><rp>(</rp><rt>か</rt><rp>)</rp></ruby>します",
    "en": "to lend, to loan, to rent out, to hire out",
    "masu": "かします"
  },
  {
    "no": 30,
    "group": "I",
    "is": false,
    "kanji": "勝ちます",
    "kanji2": "",
    "note": "",
    "vi": "thắng",
    "img": "勝ちます.jpg",
    "furigana": "<ruby><rb>勝</rb><rp>(</rp><rt>か</rt><rp>)</rp></ruby>ちます",
    "en": "to win, to gain victory",
    "masu": "かちます"
  },
  {
    "no": 31,
    "group": "I",
    "is": false,
    "kanji": "かぶります",
    "kanji2": "",
    "note": "",
    "vi": "đội (mũ, v.v.)",
    "img": "かぶります.jpg",
    "furigana": "かぶります",
    "en": "to put on (one's head), to wear, to have on, to pull over (one's head), to crown (oneself), to be covered with (dust, snow, etc.), to pour (water, etc.) on oneself, to dash on oneself, to ship water, to bear (e.g. someone's debts, faults, etc.), to take (blame), to assume (responsibility), to should...",
    "masu": "かぶります"
  },
  {
    "no": 32,
    "group": "I",
    "is": false,
    "kanji": "頑張ります",
    "kanji2": "",
    "note": "",
    "vi": "cố, cố gắng",
    "img": "頑張ります.jpg",
    "furigana": "<ruby><rb>頑張</rb><rp>(</rp><rt>がんば</rt><rp>)</rp></ruby>ります",
    "en": "to persevere, to persist, to keep at it, to hang on, to hold out, to do one's best, to insist that, to stick to (one's opinion), to remain in a place, to stick to one's post, to refuse to budge",
    "masu": "がんばります"
  },
  {
    "no": 33,
    "group": "I",
    "is": false,
    "kanji": "聞きます",
    "kanji2": "",
    "note": "",
    "vi": "nghe",
    "img": "聞きます.jpg",
    "furigana": "<ruby><rb>聞</rb><rp>(</rp><rt>き</rt><rp>)</rp></ruby>きます",
    "en": "to hear, to listen (e.g. to music), to ask, to enquire, to query, to learn of, to hear about, to follow (advice), to comply with, to smell (esp. incense), to sample fragrance",
    "masu": "ききます"
  },
  {
    "no": 34,
    "group": "I",
    "is": false,
    "kanji": "聞きます",
    "kanji2": "",
    "note": "せんせいに~",
    "vi": "hỏi [giáo viên]",
    "img": "聞きます2.jpg",
    "furigana": "<ruby><rb>聞</rb><rp>(</rp><rt>き</rt><rp>)</rp></ruby>きます",
    "en": "to hear, to listen (e.g. to music), to ask, to enquire, to query, to learn of, to hear about, to follow (advice), to comply with, to smell (esp. incense), to sample fragrance",
    "masu": "ききます"
  },
  {
    "no": 35,
    "group": "I",
    "is": false,
    "kanji": "切ります",
    "kanji2": "",
    "note": "",
    "vi": "cắt",
    "img": "切ります.jpg",
    "furigana": "<ruby><rb>切</rb><rp>(</rp><rt>き</rt><rp>)</rp></ruby>ります",
    "en": "to cut, to cut through, to perform (surgery), to sever (connections, ties), to turn off (i.e. the light), to terminate (i.e. a conversation), to hang up (the phone), to disconnect, to punch (a ticket), to tear off (a stub), to open (something sealed), to start, to set (a limit), to do (something) in...",
    "masu": "きります"
  },
  {
    "no": 36,
    "group": "I",
    "is": false,
    "kanji": "消します",
    "kanji2": "",
    "note": "",
    "vi": "tắt",
    "img": "消します.jpg",
    "furigana": "<ruby><rb>消</rb><rp>(</rp><rt>け</rt><rp>)</rp></ruby>します",
    "en": "to erase, to delete, to cross out, to turn off power, to extinguish, to put out, to bump off",
    "masu": "けします"
  },
  {
    "no": 37,
    "group": "I",
    "is": false,
    "kanji": "触ります",
    "kanji2": "",
    "note": "ドアに~",
    "vi": "sờ, chạm vào [cửa]",
    "img": "ドアに触ります.jpg",
    "furigana": "<ruby><rb>触</rb><rp>(</rp><rt>さわ</rt><rp>)</rp></ruby>ります",
    "en": "to touch, to feel",
    "masu": "さわります"
  },
  {
    "no": 38,
    "group": "I",
    "is": false,
    "kanji": "知ります",
    "kanji2": "",
    "note": "",
    "vi": "biết",
    "img": "知ります.jpg",
    "furigana": "<ruby><rb>知</rb><rp>(</rp><rt>し</rt><rp>)</rp></ruby>ります",
    "en": "to be aware of, to know, to be conscious of, to cognize, to cognise, to notice, to feel, to understand, to comprehend, to grasp, to remember, to be acquainted with (a procedure), to experience, to go through, to learn, to be acquainted with (a person), to get to know, to concern",
    "masu": "しります"
  },
  {
    "no": 39,
    "group": "I",
    "is": false,
    "kanji": "吸います",
    "kanji2": "",
    "note": "たばこを~",
    "vi": "hút [thuốc lá]",
    "img": "たばこを吸います.jpg",
    "furigana": "<ruby><rb>吸</rb><rp>(</rp><rt>す</rt><rp>)</rp></ruby>います",
    "en": "to smoke, to breathe in, to inhale, to suck, to sip, to slurp, to absorb, to soak up, to kiss",
    "masu": "すいます"
  },
  {
    "no": 40,
    "group": "I",
    "is": false,
    "kanji": "住みます",
    "kanji2": "",
    "note": "",
    "vi": "sống, ở",
    "img": "住みます.jpg",
    "furigana": "<ruby><rb>住</rb><rp>(</rp><rt>す</rt><rp>)</rp></ruby>みます",
    "en": "to live (of humans), to reside, to inhabit, to dwell, to abide",
    "masu": "すみます"
  },
  {
    "no": 41,
    "group": "I",
    "is": false,
    "kanji": "座ります",
    "kanji2": "",
    "note": "",
    "vi": "ngồi",
    "img": "座ります.jpg",
    "furigana": "<ruby><rb>座</rb><rp>(</rp><rt>すわ</rt><rp>)</rp></ruby>ります",
    "en": "to sit, to squat, to assume (a position), to hold steady, to hold still",
    "masu": "すわります"
  },
  {
    "no": 42,
    "group": "I",
    "is": false,
    "kanji": "出します",
    "kanji2": "",
    "note": "",
    "vi": "lấy ra, đưa ra, gửi",
    "img": "出します.jpg",
    "furigana": "<ruby><rb>出</rb><rp>(</rp><rt>だ</rt><rp>)</rp></ruby>します",
    "en": "to take out, to get out, to put out, to reveal, to show, to submit (e.g. thesis), to turn in, to publish, to make public, to send (e.g. letter), to produce (a sound), to start (fire), to serve (food), to begin ..., to start to ..., to burst into ...",
    "masu": "だします"
  },
  {
    "no": 43,
    "group": "I",
    "is": false,
    "kanji": "立ちます",
    "kanji2": "",
    "note": "",
    "vi": "đứng",
    "img": "立ちます.jpg",
    "furigana": "<ruby><rb>立</rb><rp>(</rp><rt>た</rt><rp>)</rp></ruby>ちます",
    "en": "to stand, to rise, to stand up, to find oneself (e.g. in a difficult position), to depart (on a plane, train, etc.)",
    "masu": "たちます"
  },
  {
    "no": 44,
    "group": "I",
    "is": false,
    "kanji": "使います",
    "kanji2": "",
    "note": "",
    "vi": "dùng, sử dụng",
    "img": "使います.jpg",
    "furigana": "<ruby><rb>使</rb><rp>(</rp><rt>つか</rt><rp>)</rp></ruby>います",
    "en": "to use (a thing, method, etc.), to make use of, to put to use, to use (a person, animal, puppet, etc.), to employ, to handle, to manage, to manipulate, to use (time, money, etc.), to spend, to consume, to use (language), to speak",
    "masu": "つかいます"
  },
  {
    "no": 45,
    "group": "I",
    "is": false,
    "kanji": "着きます",
    "kanji2": "",
    "note": "",
    "vi": "đến",
    "img": "着きます.jpg",
    "furigana": "<ruby><rb>着</rb><rp>(</rp><rt>つ</rt><rp>)</rp></ruby>きます",
    "en": "to arrive at, to reach, to sit on, to sit at (e.g. the table)",
    "masu": "つきます"
  },
  {
    "no": 46,
    "group": "I",
    "is": false,
    "kanji": "作ります",
    "kanji2": "造ります",
    "note": "",
    "vi": "làm, chế tạo, sản xuất",
    "img": "作ります.jpg",
    "furigana": "<ruby><rb>作</rb><rp>(</rp><rt>つく</rt><rp>)</rp></ruby>ります",
    "en": "to make, to produce, to manufacture, to build, to construct, to prepare (food), to brew (alcohol), to raise, to grow, to cultivate, to train, to till, to draw up (a document), to make out, to prepare, to write, to create (an artistic work, etc.), to compose, to coin (a phrase), to organize, to organ...",
    "masu": "つくります"
  },
  {
    "no": 46,
    "group": "I",
    "is": false,
    "kanji": "造ります",
    "kanji2": "作ります",
    "note": "",
    "vi": "làm, chế tạo, sản xuất",
    "img": "造ります.jpg",
    "furigana": "<ruby><rb>造</rb><rp>(</rp><rt>つく</rt><rp>)</rp></ruby>ります",
    "en": "to make, to produce, to manufacture, to build, to construct, to prepare (food), to brew (alcohol), to raise, to grow, to cultivate, to train, to till, to draw up (a document), to make out, to prepare, to write, to create (an artistic work, etc.), to compose, to coin (a phrase), to organize, to organ...",
    "masu": "つくります"
  },
  {
    "no": 47,
    "group": "I",
    "is": false,
    "kanji": "連れて行きます",
    "kanji2": "",
    "note": "",
    "vi": "dẫn (một ai đó) đi",
    "img": "連れて行きます.jpg",
    "furigana": "<ruby><rb>連</rb><rp>(</rp><rt>つ</rt><rp>)</rp></ruby>れて<ruby><rb>行</rb><rp>(</rp><rt>い</rt><rp>)</rp></ruby>きます",
    "en": "to lead, to take (a person)",
    "masu": "つれていきます"
  },
  {
    "no": 48,
    "group": "I",
    "is": false,
    "kanji": "手伝います",
    "kanji2": "",
    "note": "",
    "vi": "giúp (làm việc gì)",
    "img": "手伝います.jpg",
    "furigana": "<ruby><rb>手伝</rb><rp>(</rp><rt>てつだ</rt><rp>)</rp></ruby>います",
    "en": "to help, to assist, to aid, to contribute to, to be a factor in",
    "masu": "てつだいます"
  },
  {
    "no": 49,
    "group": "I",
    "is": false,
    "kanji": "泊まります",
    "kanji2": "",
    "note": "ホテルに~",
    "vi": "trọ [ở khách sạn]",
    "img": "ホテルに泊まります.jpg",
    "furigana": "<ruby><rb>泊</rb><rp>(</rp><rt>と</rt><rp>)</rp></ruby>まります",
    "en": "to stay at (e.g. hotel), to be docked, to be berthed, to be moored",
    "masu": "とまります"
  },
  {
    "no": 50,
    "group": "I",
    "is": false,
    "kanji": "取ります",
    "kanji2": "",
    "note": "",
    "vi": "lấy, chuyển",
    "img": "取ります.jpg",
    "furigana": "<ruby><rb>取</rb><rp>(</rp><rt>と</rt><rp>)</rp></ruby>ります",
    "en": "to take, to pick up, to harvest, to earn, to win, to choose, to steal, to eat, to have (a meal), to remove (one's glasses, etc.), to compete (in sumo, cards, etc.), to play",
    "masu": "とります"
  },
  {
    "no": 51,
    "group": "I",
    "is": false,
    "kanji": "撮ります",
    "kanji2": "",
    "note": "しゃしんを~",
    "vi": "chụp [ảnh]",
    "img": "しゃしんを撮ります.jpg",
    "furigana": "<ruby><rb>撮</rb><rp>(</rp><rt>と</rt><rp>)</rp></ruby>ります",
    "en": "to take (a photo), to record (video, audio, etc.), to make (a film)",
    "masu": "とります"
  },
  {
    "no": 52,
    "group": "I",
    "is": false,
    "kanji": "取ります",
    "kanji2": "",
    "note": "としを~",
    "vi": "có, thêm [tuổi]",
    "img": "としを取ります.jpg",
    "furigana": "<ruby><rb>取</rb><rp>(</rp><rt>と</rt><rp>)</rp></ruby>ります",
    "en": "to take, to pick up, to harvest, to earn, to win, to choose, to steal, to eat, to have (a meal), to remove (one's glasses, etc.), to compete (in sumo, cards, etc.), to play",
    "masu": "とります"
  },
  {
    "no": 53,
    "group": "I",
    "is": false,
    "kanji": "直します",
    "kanji2": "",
    "note": "",
    "vi": "chữa, sửa",
    "img": "直します.jpg",
    "furigana": "<ruby><rb>直</rb><rp>(</rp><rt>なお</rt><rp>)</rp></ruby>します",
    "en": "to cure, to heal, to fix, to correct, to repair, to do over again (after -masu base of verb), to replace, to put back as it was, to convert (into a different state), to transform",
    "masu": "なおします"
  },
  {
    "no": 54,
    "group": "I",
    "is": false,
    "kanji": "なくします",
    "kanji2": "",
    "note": "",
    "vi": "làm mất, đánh mất",
    "img": "なくします.jpg",
    "furigana": "なくします",
    "en": "to lose something, to get rid of, to lose someone (wife, child, etc.)",
    "masu": "なくします"
  },
  {
    "no": 55,
    "group": "I",
    "is": false,
    "kanji": "習います",
    "kanji2": "",
    "note": "",
    "vi": "học, tập",
    "img": "習います.jpg",
    "furigana": "<ruby><rb>習</rb><rp>(</rp><rt>なら</rt><rp>)</rp></ruby>います",
    "en": "to take lessons in, to be taught, to learn (from a teacher), to study (under a teacher), to get training in",
    "masu": "ならいます"
  },
  {
    "no": 56,
    "group": "I",
    "is": false,
    "kanji": "なります",
    "kanji2": "",
    "note": "",
    "vi": "trở thành, trở nên",
    "img": "なります.jpg",
    "furigana": "なります",
    "en": "to become, to get, to grow, to be, to reach, to attain, to result in, to prove to be, to consist of, to be composed of, to succeed, to be complete, to change into, to be exchanged for, to play a role, to be promoted, to do ...",
    "masu": "なります"
  },
  {
    "no": 57,
    "group": "I",
    "is": false,
    "kanji": "脱ぎます",
    "kanji2": "",
    "note": "",
    "vi": "cởi (quần áo, giày, v.v.)",
    "img": "脱ぎます.jpg",
    "furigana": "<ruby><rb>脱</rb><rp>(</rp><rt>ぬ</rt><rp>)</rp></ruby>ぎます",
    "en": "to take off (clothes, shoes, etc.), to undress",
    "masu": "ぬぎます"
  },
  {
    "no": 58,
    "group": "I",
    "is": false,
    "kanji": "登ります",
    "kanji2": "上ります",
    "note": "",
    "vi": "leo (núi), lên",
    "img": "上ります.jpg",
    "furigana": "<ruby><rb>登</rb><rp>(</rp><rt>のぼ</rt><rp>)</rp></ruby>ります",
    "en": "to ascend, to go up, to climb, to ascend (as a natural process, e.g. the sun), to rise, to go to (the capital), to be promoted, to add up to, to advance (in price), to swim up (a river), to sail up, to come up (on the agenda)",
    "masu": "のぼります"
  },
  {
    "no": 59,
    "group": "I",
    "is": false,
    "kanji": "飲みます",
    "kanji2": "",
    "note": "",
    "vi": "uống",
    "img": "飲みます.jpg",
    "furigana": "<ruby><rb>飲</rb><rp>(</rp><rt>の</rt><rp>)</rp></ruby>みます",
    "en": "to drink, to gulp, to swallow, to take (medicine), to smoke (tobacco), to engulf, to overwhelm, to keep down, to suppress, to accept (e.g. demand, condition), to make light of, to conceal",
    "masu": "のみます"
  },
  {
    "no": 60,
    "group": "I",
    "is": false,
    "kanji": "乗ります",
    "kanji2": "",
    "note": "バスに~",
    "vi": "đi, lên [tàu]",
    "img": "バスに乗ります.jpg",
    "furigana": "<ruby><rb>乗</rb><rp>(</rp><rt>の</rt><rp>)</rp></ruby>ります",
    "en": "to get on (train, plane, bus, ship, etc.), to get in, to board, to take, to embark, to get on (e.g. a footstool), to step on, to jump on, to sit on, to mount, to reach, to go over, to pass, to follow, to stay (on track), to go with (the times, etc.), to take part, to participate, to join, to get int...",
    "masu": "のります"
  },
  {
    "no": 61,
    "group": "I",
    "is": false,
    "kanji": "入ります",
    "kanji2": "",
    "note": "鏡に~",
    "vi": "vào [quán giải khát]",
    "img": "鏡に入ります.jpg",
    "furigana": "<ruby><rb>入</rb><rp>(</rp><rt>はい</rt><rp>)</rp></ruby>ります",
    "en": "to get in, to go in, to come in, to flow into, to set, to set in",
    "masu": "はいります"
  },
  {
    "no": 62,
    "group": "I",
    "is": false,
    "kanji": "入ります",
    "kanji2": "",
    "note": "おふろに~",
    "vi": "tắm bồn",
    "img": "おふろに入ります.jpg",
    "furigana": "<ruby><rb>入</rb><rp>(</rp><rt>はい</rt><rp>)</rp></ruby>ります",
    "en": "to get in, to go in, to come in, to flow into, to set, to set in",
    "masu": "はいります"
  },
  {
    "no": 63,
    "group": "I",
    "is": false,
    "kanji": "はきます",
    "kanji2": "",
    "note": "",
    "vi": "đi, mặc (giày, quần âu, v.v.)",
    "img": "はきます.jpg",
    "furigana": "はきます",
    "en": "to sweep, to brush, to gather up",
    "masu": "はきます"
  },
  {
    "no": 64,
    "group": "I",
    "is": false,
    "kanji": "働きます",
    "kanji2": "",
    "note": "",
    "vi": "làm việc",
    "img": "働きます.jpg",
    "furigana": "<ruby><rb>働</rb><rp>(</rp><rt>はたら</rt><rp>)</rp></ruby>きます",
    "en": "to work, to labor, to labour, to function, to operate, to be effective, to work (i.e. ... works), to come into play, to commit (e.g. a crime), to perpetrate, to do, to act, to practise, to practice, to be conjugated",
    "masu": "はたらきます"
  },
  {
    "no": 65,
    "group": "I",
    "is": false,
    "kanji": "話します",
    "kanji2": "",
    "note": "",
    "vi": "nói , nói chuyện",
    "img": "話します.jpg",
    "furigana": "<ruby><rb>話</rb><rp>(</rp><rt>はな</rt><rp>)</rp></ruby>します",
    "en": "to talk, to speak, to converse, to chat, to tell, to explain, to narrate, to mention, to describe, to discuss, to speak (a language)",
    "masu": "はなします"
  },
  {
    "no": 66,
    "group": "I",
    "is": false,
    "kanji": "払います",
    "kanji2": "",
    "note": "",
    "vi": "trả tiền",
    "img": "払います.jpg",
    "furigana": "<ruby><rb>払</rb><rp>(</rp><rt>はら</rt><rp>)</rp></ruby>います",
    "en": "to pay (e.g. money, bill), to brush off, to wipe away, to clear away, to dust off, to cut off (e.g. branches), to drive away (e.g. one's competitors), to sell off (something unneeded), to dispose of, to pay (e.g. attention), to show (e.g. respect, concern), to make (e.g. effort, sacrifice), to expen...",
    "masu": "はらいます"
  },
  {
    "no": 67,
    "group": "I",
    "is": false,
    "kanji": "弾きます",
    "kanji2": "",
    "note": "",
    "vi": "chơi ( nhạc cụ , pianô , vv . )",
    "img": "弾きます.jpg",
    "furigana": "<ruby><rb>弾</rb><rp>(</rp><rt>はじ</rt><rp>)</rp></ruby>きます",
    "en": "to flip, to snap, to flick, to repel, to use (an abacus), to calculate, to strum, to pluck the strings (of a guitar, etc.)",
    "masu": "はじきます"
  },
  {
    "no": 68,
    "group": "I",
    "is": false,
    "kanji": "引きます",
    "kanji2": "",
    "note": "",
    "vi": "kéo",
    "img": "引きます.jpg",
    "furigana": "<ruby><rb>引</rb><rp>(</rp><rt>ひ</rt><rp>)</rp></ruby>きます",
    "en": "to pull, to draw (attention, etc.), to attract (interest, etc.), to draw back, to draw (a card), to draw (plan, line, etc.), to catch (cold), to play (string instr.), to look up (e.g. dictionary), to consult, to haul, to pull (vehicles), to subtract, to ebb, to fade, to descend (from), to inherit (a...",
    "masu": "ひきます"
  },
  {
    "no": 69,
    "group": "I",
    "is": false,
    "kanji": "降ります",
    "kanji2": "",
    "note": "あめが~",
    "vi": "mưa",
    "img": "あめが降ります.jpg",
    "furigana": "<ruby><rb>降</rb><rp>(</rp><rt>お</rt><rp>)</rp></ruby>ります",
    "en": "to descend (e.g. a mountain), to go down, to come down, to alight (e.g. from bus), to get off, to disembark, to dismount, to step down, to retire, to give up, to quit, to be granted, to be issued, to be given, to form (of frost, dew, mist, etc.), to be passed (from the body; e.g. of a roundworm)",
    "masu": "おります"
  },
  {
    "no": 70,
    "group": "I",
    "is": false,
    "kanji": "曲がります",
    "kanji2": "",
    "note": "みぎへ~",
    "vi": "rẽ , quẹo [ phải ]",
    "img": "みぎへ曲がります.jpg",
    "furigana": "<ruby><rb>曲</rb><rp>(</rp><rt>ま</rt><rp>)</rp></ruby>がります",
    "en": "to bend, to curve, to warp, to wind, to twist, to turn, to be awry, to be askew, to be crooked",
    "masu": "まがります"
  },
  {
    "no": 71,
    "group": "I",
    "is": false,
    "kanji": "待ちます",
    "kanji2": "",
    "note": "",
    "vi": "đợi , chờ",
    "img": "待ちます.jpg",
    "furigana": "<ruby><rb>待</rb><rp>(</rp><rt>ま</rt><rp>)</rp></ruby>ちます",
    "en": "to wait, to await, to look forward to, to anticipate, to depend on, to need",
    "masu": "まちます"
  },
  {
    "no": 72,
    "group": "I",
    "is": false,
    "kanji": "回します",
    "kanji2": "",
    "note": "",
    "vi": "vặn",
    "img": "回します.jpg",
    "furigana": "<ruby><rb>回</rb><rp>(</rp><rt>まわ</rt><rp>)</rp></ruby>します",
    "en": "to turn, to rotate, to gyrate, to circulate, to send around, to surround, to put something to a new use (e.g. leftovers), ... around (e.g. to chase someone around), to dial (e.g. telephone number), to invest, to gang-rape",
    "masu": "まわします"
  },
  {
    "no": 73,
    "group": "I",
    "is": false,
    "kanji": "持ちます",
    "kanji2": "",
    "note": "",
    "vi": "mang , cầm",
    "img": "持ちます.jpg",
    "furigana": "<ruby><rb>持</rb><rp>(</rp><rt>も</rt><rp>)</rp></ruby>ちます",
    "en": "to hold (in one's hand), to take, to carry, to possess, to have, to own, to maintain, to keep, to last, to be durable, to keep, to survive, to take charge of, to be in charge of",
    "masu": "もちます"
  },
  {
    "no": 74,
    "group": "I",
    "is": false,
    "kanji": "持って行きます",
    "kanji2": "",
    "note": "",
    "vi": "mang đi , mang theo",
    "img": "持って行きます.jpg",
    "furigana": "<ruby><rb>持</rb><rp>(</rp><rt>も</rt><rp>)</rp></ruby>って<ruby><rb>行</rb><rp>(</rp><rt>い</rt><rp>)</rp></ruby>きます",
    "en": "to hold (in one's hand), to take, to carry, to possess, to have, to own, to maintain, to keep, to last, to be durable, to keep, to survive, to take charge of, to be in charge of",
    "masu": "もっていきます"
  },
  {
    "no": 75,
    "group": "I",
    "is": false,
    "kanji": "もらいます",
    "kanji2": "",
    "note": "",
    "vi": "nhận",
    "img": "もらいます.jpg",
    "furigana": "もらいます",
    "en": "to receive, to take, to accept, to get somebody to do something",
    "masu": "もらいます"
  },
  {
    "no": 76,
    "group": "I",
    "is": false,
    "kanji": "役に立ちます",
    "kanji2": "",
    "note": "",
    "vi": "hữu ích , giúp ích",
    "img": "役に立ちます.jpg",
    "furigana": "<ruby><rb>役</rb><rp>(</rp><rt>やく</rt><rp>)</rp></ruby>に<ruby><rb>立</rb><rp>(</rp><rt>た</rt><rp>)</rp></ruby>ちます",
    "en": "to be helpful, to be useful",
    "masu": "やくにたちます"
  },
  {
    "no": 77,
    "group": "I",
    "is": false,
    "kanji": "休みます",
    "kanji2": "",
    "note": "",
    "vi": "nghỉ , nghỉ ngơi",
    "img": "休みます.jpg",
    "furigana": "<ruby><rb>休</rb><rp>(</rp><rt>やす</rt><rp>)</rp></ruby>みます",
    "en": "to be absent, to take a day off, to rest, to have a break, to go to bed, to (lie down to) sleep, to turn in, to retire, to stop doing some ongoing activity for a time, to suspend business",
    "masu": "やすみます"
  },
  {
    "no": 78,
    "group": "I",
    "is": false,
    "kanji": "休みます",
    "kanji2": "",
    "note": "かいしゃを~",
    "vi": "nghỉ [ làm việc]",
    "img": "かいしゃを休みます.jpg",
    "furigana": "<ruby><rb>休</rb><rp>(</rp><rt>やす</rt><rp>)</rp></ruby>みます",
    "en": "to be absent, to take a day off, to rest, to have a break, to go to bed, to (lie down to) sleep, to turn in, to retire, to stop doing some ongoing activity for a time, to suspend business",
    "masu": "やすみます"
  },
  {
    "no": 79,
    "group": "I",
    "is": false,
    "kanji": "呼びます",
    "kanji2": "",
    "note": "",
    "vi": "gọi",
    "img": "呼びます.jpg",
    "furigana": "<ruby><rb>呼</rb><rp>(</rp><rt>よ</rt><rp>)</rp></ruby>びます",
    "en": "to call out (to), to call, to invoke, to summon (a doctor, etc.), to invite, to designate, to name, to brand, to garner (support, etc.), to gather, to take as one's wife",
    "masu": "よびます"
  },
  {
    "no": 80,
    "group": "I",
    "is": false,
    "kanji": "読みます",
    "kanji2": "",
    "note": "",
    "vi": "đọc",
    "img": "読みます.jpg",
    "furigana": "<ruby><rb>読</rb><rp>(</rp><rt>よ</rt><rp>)</rp></ruby>みます",
    "en": "to read, to count, to guess, to predict, to read (someone's thoughts), to see (e.g. into someone's heart), to divine",
    "masu": "よみます"
  },
  {
    "no": 81,
    "group": "I",
    "is": false,
    "kanji": "わかります",
    "kanji2": "",
    "note": "",
    "vi": "hiểu , nắm được",
    "img": "わかります.jpg",
    "furigana": "わかります",
    "en": "to understand, to comprehend, to grasp, to see, to get, to follow, to become clear, to be known, to be discovered, to be realized, to be realised, to be found out",
    "masu": "わかります"
  },
  {
    "no": 82,
    "group": "I",
    "is": false,
    "kanji": "渡ります",
    "kanji2": "",
    "note": "はしを~",
    "vi": "qua , đi qua [ cầu ]",
    "img": "はしを渡ります.jpg",
    "furigana": "<ruby><rb>渡</rb><rp>(</rp><rt>わた</rt><rp>)</rp></ruby>ります",
    "en": "to cross over, to go across, to extend, to cover, to range, to span",
    "masu": "わたります"
  },
  {
    "no": 1,
    "group": "II",
    "is": false,
    "kanji": "開けます",
    "kanji2": "",
    "note": "",
    "vi": "mở",
    "img": "開けます.jpg",
    "furigana": "<ruby><rb>開</rb><rp>(</rp><rt>あ</rt><rp>)</rp></ruby>けます",
    "en": "to open, to bare, to expose, to stretch",
    "masu": "あけます"
  },
  {
    "no": 2,
    "group": "II",
    "is": false,
    "kanji": "あげます",
    "kanji2": "",
    "note": "",
    "vi": "cho , tặng",
    "img": "あげます.jpg",
    "furigana": "あげます",
    "en": "to raise, to elevate, to do up (one's hair), to fly (a kite, etc.), to launch (fireworks, etc.), to surface (a submarine, etc.), to land (a boat), to deep-fry, to show someone (into a room), to summon (for geishas, etc.), to send someone (away), to enrol (one's child in school), to enroll, to increa...",
    "masu": "あげます"
  },
  {
    "no": 3,
    "group": "II",
    "is": false,
    "kanji": "集めます",
    "kanji2": "",
    "note": "",
    "vi": "sưu tầm , thu thập , tập hợp",
    "img": "集めます.jpg",
    "furigana": "<ruby><rb>集</rb><rp>(</rp><rt>あつ</rt><rp>)</rp></ruby>めます",
    "en": "to collect, to assemble, to gather",
    "masu": "あつめます"
  },
  {
    "no": 4,
    "group": "II",
    "is": true,
    "kanji": "浴びます",
    "kanji2": "",
    "note": "シャワーを~",
    "vi": "tắm [ vòi hoa sen ]",
    "img": "シャワーを浴びます.jpg",
    "furigana": "<ruby><rb>浴</rb><rp>(</rp><rt>あ</rt><rp>)</rp></ruby>びます",
    "en": "to dash over oneself (e.g. water), to take (e.g. shower), to bask in (e.g. the sun), to bathe in, to be flooded with (e.g. light), to be covered in, to suffer (e.g. an attack), to draw (e.g. criticism, attention, praise), to have heaped upon, to be showered with",
    "masu": "あびます"
  },
  {
    "no": 5,
    "group": "II",
    "is": true,
    "kanji": "います",
    "kanji2": "",
    "note": "",
    "vi": "ở, có con, sống ở",
    "img": "います.jpg",
    "furigana": "います",
    "en": "to need, to want",
    "masu": "います"
  },
  {
    "no": 6,
    "group": "II",
    "is": false,
    "kanji": "入れます",
    "kanji2": "",
    "note": "",
    "vi": "cho vào , bỏ vào",
    "img": "入れます.jpg",
    "furigana": "<ruby><rb>入</rb><rp>(</rp><rt>い</rt><rp>)</rp></ruby>れます",
    "en": "to put in, to let in, to take in, to bring in, to insert, to set (a jewel, etc.), to ink in (e.g. a tattoo), to admit, to accept, to employ, to hire, to accept, to comply, to grant, to adopt (a policy, etc.), to take (advice, etc.), to listen to, to pay attention to, to include, to pay (one's rent, ...",
    "masu": "いれます"
  },
  {
    "no": 7,
    "group": "II",
    "is": false,
    "kanji": "生まれます",
    "kanji2": "",
    "note": "",
    "vi": "sinh ra",
    "img": "生まれます.jpg",
    "furigana": "<ruby><rb>生</rb><rp>(</rp><rt>う</rt><rp>)</rp></ruby>まれます",
    "en": "to be born",
    "masu": "うまれます"
  },
  {
    "no": 8,
    "group": "II",
    "is": true,
    "kanji": "起きます",
    "kanji2": "",
    "note": "",
    "vi": "dậy , thức dậy",
    "img": "起きます.jpg",
    "furigana": "<ruby><rb>起</rb><rp>(</rp><rt>お</rt><rp>)</rp></ruby>きます",
    "en": "to get up, to rise, to blaze up (fire), to wake up, to be awake, to stay awake, to occur (usu. of unfavourable incidents), to happen, to take place",
    "masu": "おきます"
  },
  {
    "no": 9,
    "group": "II",
    "is": false,
    "kanji": "教えます",
    "kanji2": "",
    "note": "",
    "vi": "dạy",
    "img": "教えます.jpg",
    "furigana": "<ruby><rb>教</rb><rp>(</rp><rt>おし</rt><rp>)</rp></ruby>えます",
    "en": "to teach, to inform, to instruct",
    "masu": "おしえます"
  },
  {
    "no": 10,
    "group": "II",
    "is": false,
    "kanji": "教えます",
    "kanji2": "",
    "note": "じゅうしょを~",
    "vi": "nói , cho biết [ địa chỉ ]",
    "img": "じゅうしょを教えます.jpg",
    "furigana": "<ruby><rb>教</rb><rp>(</rp><rt>おし</rt><rp>)</rp></ruby>えます",
    "en": "to teach, to inform, to instruct",
    "masu": "おしえます"
  },
  {
    "no": 11,
    "group": "II",
    "is": false,
    "kanji": "覚えます",
    "kanji2": "",
    "note": "",
    "vi": "nhớ",
    "img": "覚えます.jpg",
    "furigana": "<ruby><rb>覚</rb><rp>(</rp><rt>おぼ</rt><rp>)</rp></ruby>えます",
    "en": "to memorize, to memorise, to commit to memory, to learn by heart, to bear in mind, to remember, to learn, to pick up, to acquire, to feel, to think, to regard",
    "masu": "おぼえます"
  },
  {
    "no": 12,
    "group": "II",
    "is": true,
    "kanji": "降ります",
    "kanji2": "",
    "note": "バスを~",
    "vi": "xuống [ tàu ]",
    "img": "バスを降ります.jpg",
    "furigana": "<ruby><rb>降</rb><rp>(</rp><rt>お</rt><rp>)</rp></ruby>ります",
    "en": "to descend (e.g. a mountain), to go down, to come down, to alight (e.g. from bus), to get off, to disembark, to dismount, to step down, to retire, to give up, to quit, to be granted, to be issued, to be given, to form (of frost, dew, mist, etc.), to be passed (from the body; e.g. of a roundworm)",
    "masu": "おります"
  },
  {
    "no": 13,
    "group": "II",
    "is": false,
    "kanji": "換えます",
    "kanji2": "",
    "note": "",
    "vi": "đổi , trao đổi",
    "img": "換えます.jpg",
    "furigana": "<ruby><rb>換</rb><rp>(</rp><rt>か</rt><rp>)</rp></ruby>えます",
    "en": "to replace, to exchange, to interchange, to substitute",
    "masu": "かえます"
  },
  {
    "no": 14,
    "group": "II",
    "is": false,
    "kanji": "変えます",
    "kanji2": "",
    "note": "",
    "vi": "đổi",
    "img": "変えます.jpg",
    "furigana": "<ruby><rb>変</rb><rp>(</rp><rt>か</rt><rp>)</rp></ruby>えます",
    "en": "to change, to alter, to transform, to convert, to turn, to vary, to reform, to revise, to amend",
    "masu": "かえます"
  },
  {
    "no": 15,
    "group": "II",
    "is": false,
    "kanji": "でんわをかけます",
    "kanji2": "",
    "note": "でんわを~",
    "vi": "gọi [điện thoại ]",
    "img": "でんわをかけます.jpg",
    "furigana": "でんわをかけます",
    "en": "to hang (e.g. picture), to hoist (e.g. sail), to raise (e.g. flag), to sit, to take (time, money), to expend (money, time, etc.), to make (a call), to multiply, to secure (e.g. lock), to put on (glasses, etc.), to cover, to burden someone, to apply (insurance), to turn on (an engine, etc.), to set (...",
    "masu": "でんわをかけます"
  },
  {
    "no": 16,
    "group": "II",
    "is": false,
    "kanji": "かけます",
    "kanji2": "",
    "note": "めがねを~",
    "vi": "đeo [ kính ]",
    "img": "めがねをかけます.jpg",
    "furigana": "かけます",
    "en": "to suspend between two points, to build (a bridge, etc.), to put up on something (e.g. legs up on table)",
    "masu": "かけます"
  },
  {
    "no": 17,
    "group": "II",
    "is": true,
    "kanji": "借ります",
    "kanji2": "",
    "note": "",
    "vi": "mượn , vay",
    "img": "借ります.jpg",
    "furigana": "<ruby><rb>借</rb><rp>(</rp><rt>か</rt><rp>)</rp></ruby>ります",
    "en": "to borrow, to have a loan, to rent, to hire",
    "masu": "かります"
  },
  {
    "no": 18,
    "group": "II",
    "is": false,
    "kanji": "考えます",
    "kanji2": "",
    "note": "",
    "vi": "nghĩ , suy nghĩ",
    "img": "考えます.jpg",
    "furigana": "<ruby><rb>考</rb><rp>(</rp><rt>かんが</rt><rp>)</rp></ruby>えます",
    "en": "to think about, to take into consideration, to ponder, to reflect, to try to come at a conclusion, to think over (something), to intend, to decide (to do), to plan, to come up with, to devise, to scheme, to predict, to anticipate, to expect, to suspect, to doubt, to consider (somebody to be somethin...",
    "masu": "かんがえます"
  },
  {
    "no": 19,
    "group": "II",
    "is": true,
    "kanji": "着ます",
    "kanji2": "",
    "note": "",
    "vi": "mặc (áo sơ mi, vv.)",
    "img": "着ます.jpg",
    "furigana": "<ruby><rb>着</rb><rp>(</rp><rt>き</rt><rp>)</rp></ruby>ます",
    "en": "to wear (in modern Japanese, from the shoulders down), to put on, to bear (guilt, etc.)",
    "masu": "きます"
  },
  {
    "no": 20,
    "group": "II",
    "is": false,
    "kanji": "気をつけます",
    "kanji2": "",
    "note": "",
    "vi": "chú ý , bảo trọng",
    "img": "気をつけます.jpg",
    "furigana": "<ruby><rb>気</rb><rp>(</rp><rt>き</rt><rp>)</rp></ruby>をつけます",
    "en": "to turn on, to switch on, to light up",
    "masu": "きをつけます"
  },
  {
    "no": 21,
    "group": "II",
    "is": false,
    "kanji": "くれます",
    "kanji2": "",
    "note": "",
    "vi": "cho , tặng ( tôi )",
    "img": "くれます.jpg",
    "furigana": "くれます",
    "en": "to give, to let one have, to do for one, to be given",
    "masu": "くれます"
  },
  {
    "no": 22,
    "group": "II",
    "is": false,
    "kanji": "閉めます",
    "kanji2": "",
    "note": "",
    "vi": "đóng (cửa , cửa sổ )",
    "img": "閉めます.jpg",
    "furigana": "<ruby><rb>閉</rb><rp>(</rp><rt>し</rt><rp>)</rp></ruby>めます",
    "en": "to close, to shut",
    "masu": "しめます"
  },
  {
    "no": 23,
    "group": "II",
    "is": false,
    "kanji": "調べます",
    "kanji2": "",
    "note": "",
    "vi": "tìm hiểu , kiểm tra , điều tra",
    "img": "調べます.jpg",
    "furigana": "<ruby><rb>調</rb><rp>(</rp><rt>しら</rt><rp>)</rp></ruby>べます",
    "en": "to examine, to investigate, to check up, to sense, to study, to inquire, to search",
    "masu": "しらべます"
  },
  {
    "no": 24,
    "group": "II",
    "is": false,
    "kanji": "捨てます",
    "kanji2": "",
    "note": "",
    "vi": "vứt , bỏ , bỏ đi",
    "img": "捨てます.jpg",
    "furigana": "<ruby><rb>捨</rb><rp>(</rp><rt>す</rt><rp>)</rp></ruby>てます",
    "en": "to throw away, to cast away, to dump, to discard, to abandon, to desert, to leave, to give up, to resign",
    "masu": "すてます"
  },
  {
    "no": 25,
    "group": "II",
    "is": false,
    "kanji": "食べます",
    "kanji2": "",
    "note": "",
    "vi": "ăn",
    "img": "食べます.jpg",
    "furigana": "<ruby><rb>食</rb><rp>(</rp><rt>た</rt><rp>)</rp></ruby>べます",
    "en": "to eat, to live on (e.g. a salary), to live off, to subsist on",
    "masu": "たべます"
  },
  {
    "no": 26,
    "group": "II",
    "is": true,
    "kanji": "足ります",
    "kanji2": "",
    "note": "",
    "vi": "đủ",
    "img": "足りない.jpg",
    "furigana": "<ruby><rb>足</rb><rp>(</rp><rt>た</rt><rp>)</rp></ruby>ります",
    "en": "to be sufficient, to be enough, to be worth doing, to be worthy, to be sufficient, to answer, to do",
    "masu": "たります"
  },
  {
    "no": 27,
    "group": "II",
    "is": false,
    "kanji": "疲れます",
    "kanji2": "",
    "note": "",
    "vi": "mệt",
    "img": "疲れます.jpg",
    "furigana": "<ruby><rb>疲</rb><rp>(</rp><rt>つか</rt><rp>)</rp></ruby>れます",
    "en": "to get tired, to tire, to be worn out (e.g. of well used objects), to starve",
    "masu": "つかれます"
  },
  {
    "no": 28,
    "group": "II",
    "is": false,
    "kanji": "つけます",
    "kanji2": "",
    "note": "",
    "vi": "bật",
    "img": "つけます.jpg",
    "furigana": "つけます",
    "en": "to turn on, to switch on, to light up",
    "masu": "つけます"
  },
  {
    "no": 29,
    "group": "II",
    "is": false,
    "kanji": "出かけます",
    "kanji2": "",
    "note": "",
    "vi": "ra ngoài",
    "img": "出かけます.jpg",
    "furigana": "<ruby><rb>出</rb><rp>(</rp><rt>で</rt><rp>)</rp></ruby>かけます",
    "en": "to go out (e.g. on an excursion or outing), to leave, to depart, to start, to set out, to be about to leave, to be just going out",
    "masu": "でかけます"
  },
  {
    "no": 30,
    "group": "II",
    "is": true,
    "kanji": "できます",
    "kanji2": "",
    "note": "",
    "vi": "có thể",
    "img": "できます.jpg",
    "furigana": "できます",
    "en": "to be able (in a position) to do, to be up to the task, to be ready, to be completed, to be made, to be built, to be good at, to be permitted (to do), to become intimate, to take up (with somebody), to grow, to be raised, to become pregnant",
    "masu": "できます"
  },
  {
    "no": 31,
    "group": "II",
    "is": false,
    "kanji": "出ます",
    "kanji2": "",
    "note": "おつりが~",
    "vi": "[tiền thừa ] ra , chạy ra",
    "img": "おつりが出ます.jpg",
    "furigana": "<ruby><rb>出</rb><rp>(</rp><rt>で</rt><rp>)</rp></ruby>ます",
    "en": "to leave, to exit, to go out, to come out, to get out, to leave (on a journey), to depart, to start out, to set out, to move forward, to come to, to get to, to lead to, to reach, to appear, to come out, to emerge, to surface, to come forth, to turn up, to be found, to be detected, to be discovered, ...",
    "masu": "でます"
  },
  {
    "no": 32,
    "group": "II",
    "is": false,
    "kanji": "出ます",
    "kanji2": "",
    "note": "きっさてんを~",
    "vi": "ra , ra khỏi [ quán giải khát ]",
    "img": "出ます.jpg",
    "furigana": "<ruby><rb>出</rb><rp>(</rp><rt>で</rt><rp>)</rp></ruby>ます",
    "en": "to leave, to exit, to go out, to come out, to get out, to leave (on a journey), to depart, to start out, to set out, to move forward, to come to, to get to, to lead to, to reach, to appear, to come out, to emerge, to surface, to come forth, to turn up, to be found, to be detected, to be discovered, ...",
    "masu": "でます"
  },
  {
    "no": 33,
    "group": "II",
    "is": false,
    "kanji": "出ます",
    "kanji2": "",
    "note": "だいがくを~",
    "vi": "ra , tốt nghiệp [đại học ]",
    "img": "だいがくを出ます.jpg",
    "furigana": "<ruby><rb>出</rb><rp>(</rp><rt>で</rt><rp>)</rp></ruby>ます",
    "en": "to leave, to exit, to go out, to come out, to get out, to leave (on a journey), to depart, to start out, to set out, to move forward, to come to, to get to, to lead to, to reach, to appear, to come out, to emerge, to surface, to come forth, to turn up, to be found, to be detected, to be discovered, ...",
    "masu": "でます"
  },
  {
    "no": 34,
    "group": "II",
    "is": false,
    "kanji": "止めます",
    "kanji2": "",
    "note": "",
    "vi": "dừng , đỗ",
    "img": "止めます.jpg",
    "furigana": "<ruby><rb>止</rb><rp>(</rp><rt>と</rt><rp>)</rp></ruby>めます",
    "en": "to stop, to turn off, to park, to prevent, to suppress (a cough), to hold back (tears), to hold (one's breath), to relieve (pain), to stop (someone from doing something), to dissuade, to forbid, to prohibit, to notice, to be aware of, to concentrate on, to pay attention to, to remember, to bear in m...",
    "masu": "とめます"
  },
  {
    "no": 35,
    "group": "II",
    "is": false,
    "kanji": "寝ます",
    "kanji2": "",
    "note": "",
    "vi": "ngủ , đi ngủ",
    "img": "寝ます.jpg",
    "furigana": "<ruby><rb>寝</rb><rp>(</rp><rt>ね</rt><rp>)</rp></ruby>ます",
    "en": "to lie down, to go to bed, to lie in bed, to sleep (lying down), to sleep (with someone, i.e. have intercourse), to lie idle",
    "masu": "ねます"
  },
  {
    "no": 36,
    "group": "II",
    "is": false,
    "kanji": "乗り換えます",
    "kanji2": "",
    "note": "",
    "vi": "chuyển , đổi ( tàu )",
    "img": "乗り換えます.jpg",
    "furigana": "<ruby><rb>乗</rb><rp>(</rp><rt>の</rt><rp>)</rp></ruby>り<ruby><rb>換</rb><rp>(</rp><rt>か</rt><rp>)</rp></ruby>えます",
    "en": "to transfer (trains), to change (bus, train), to change one's mind, to move on to (e.g. a new love interest), to change methods, to change one's way of thinking",
    "masu": "のりかえます"
  },
  {
    "no": 37,
    "group": "II",
    "is": false,
    "kanji": "始めます",
    "kanji2": "",
    "note": "",
    "vi": "bắt đầu",
    "img": "始めます.jpg",
    "furigana": "<ruby><rb>始</rb><rp>(</rp><rt>はじ</rt><rp>)</rp></ruby>めます",
    "en": "to start, to begin, to commence, to initiate, to originate, to open (e.g. a store), to start up, to establish (business. etc.), to start ..., to begin to ...",
    "masu": "はじめます"
  },
  {
    "no": 38,
    "group": "II",
    "is": false,
    "kanji": "負けます",
    "kanji2": "",
    "note": "",
    "vi": "thua",
    "img": "負けます.jpg",
    "furigana": "<ruby><rb>負</rb><rp>(</rp><rt>ま</rt><rp>)</rp></ruby>けます",
    "en": "to lose, to be defeated, to succumb, to give in, to surrender, to yield, to be inferior to, to break out in a rash due to (e.g. lacquer, shaving, etc.), to reduce the price, to lower the price, to give a discount on",
    "masu": "まけます"
  },
  {
    "no": 39,
    "group": "II",
    "is": false,
    "kanji": "見せます",
    "kanji2": "",
    "note": "",
    "vi": "cho xem , trình",
    "img": "見せます.jpg",
    "furigana": "<ruby><rb>見</rb><rp>(</rp><rt>み</rt><rp>)</rp></ruby>せます",
    "en": "to show, to display",
    "masu": "みせます"
  },
  {
    "no": 40,
    "group": "II",
    "is": true,
    "kanji": "見ます",
    "kanji2": "",
    "note": "",
    "vi": "nhìn , xem",
    "img": "見ます.jpg",
    "furigana": "<ruby><rb>見</rb><rp>(</rp><rt>み</rt><rp>)</rp></ruby>ます",
    "en": "to see, to look, to watch, to view, to observe, to look over, to look on, to assess, to examine, to judge, to look after, to keep an eye on, to take care of, to view (e.g. flowers, movie), to try, to try out, to see that..., to find that...",
    "masu": "みます"
  },
  {
    "no": 41,
    "group": "II",
    "is": false,
    "kanji": "迎えます",
    "kanji2": "",
    "note": "",
    "vi": "đón",
    "img": "迎えます.jpg",
    "furigana": "<ruby><rb>迎</rb><rp>(</rp><rt>むか</rt><rp>)</rp></ruby>えます",
    "en": "to go out to meet, to receive, to welcome, to greet, to salute, to hail, to reach, to approach, to enter (a phase, era, etc.), to accept (e.g. as a member of a group or family), to call for, to summon, to invite, to approach (a certain time, a point in one's life, etc.)",
    "masu": "むかえます"
  },
  {
    "no": 42,
    "group": "II",
    "is": false,
    "kanji": "やめます",
    "kanji2": "",
    "note": "かいしゃを~",
    "vi": "bỏ , thôi [ việc công ty]",
    "img": "かいしゃをやめます.jpg",
    "furigana": "やめます",
    "en": "to stop (an activity), to cease, to discontinue, to end, to quit, to cancel, to abandon, to give up, to abolish, to abstain, to refrain",
    "masu": "やめます"
  },
  {
    "no": 43,
    "group": "II",
    "is": false,
    "kanji": "忘れます",
    "kanji2": "",
    "note": "",
    "vi": "quên",
    "img": "忘れます.jpg",
    "furigana": "<ruby><rb>忘</rb><rp>(</rp><rt>わす</rt><rp>)</rp></ruby>れます",
    "en": "to forget, to leave carelessly, to be forgetful of, to forget about, to forget (an article)",
    "masu": "わすれます"
  },
  {
    "no": 1,
    "group": "III",
    "is": false,
    "kanji": "案内します",
    "kanji2": "",
    "note": "",
    "vi": "hướng dẫn , giới thiệu , dẫn đường",
    "img": "案内します.jpg",
    "furigana": "<ruby><rb>案内</rb><rp>(</rp><rt>あんない</rt><rp>)</rp></ruby>します",
    "en": "information, guidance, leading, to guide, to show (around), to conduct",
    "masu": "あんないします"
  },
  {
    "no": 2,
    "group": "III",
    "is": false,
    "kanji": "運転します",
    "kanji2": "",
    "note": "",
    "vi": "lái",
    "img": "運転します.jpg",
    "furigana": "<ruby><rb>運転</rb><rp>(</rp><rt>うんてん</rt><rp>)</rp></ruby>します",
    "en": "operation (of a machine, etc.), operating, running, run, driving, working (capital, etc.)",
    "masu": "うんてんします"
  },
  {
    "no": 3,
    "group": "III",
    "is": false,
    "kanji": "買い物します",
    "kanji2": "",
    "note": "",
    "vi": "mua sắm , mua hàng",
    "img": "買い物します.jpg",
    "furigana": "<ruby><rb>買</rb><rp>(</rp><rt>か</rt><rp>)</rp></ruby>い<ruby><rb>物</rb><rp>(</rp><rt>もの</rt><rp>)</rp></ruby>します",
    "en": "shopping, purchased goods",
    "masu": "かいものします"
  },
  {
    "no": 4,
    "group": "III",
    "is": true,
    "kanji": "来ます",
    "kanji2": "",
    "note": "",
    "vi": "đến",
    "img": "来ます.jpg",
    "furigana": "<ruby><rb>来</rb><rp>(</rp><rt>き</rt><rp>)</rp></ruby>ます",
    "en": "to come (spatially or temporally), to approach, to arrive, to come back, to do ... and come back, to come to be, to become, to get, to grow, to continue, to come from, to be caused by, to derive from, to come to (i.e. &quot;when it comes to spinach ...&quot;)",
    "masu": "きます"
  },
  {
    "no": 5,
    "group": "III",
    "is": false,
    "kanji": "結婚します",
    "kanji2": "",
    "note": "",
    "vi": "kết hôn , lập gia đình , cưới",
    "img": "結婚します.jpg",
    "furigana": "<ruby><rb>結婚</rb><rp>(</rp><rt>けっこん</rt><rp>)</rp></ruby>します",
    "en": "marriage",
    "masu": "けっこんします"
  },
  {
    "no": 6,
    "group": "III",
    "is": false,
    "kanji": "見学します",
    "kanji2": "",
    "note": "",
    "vi": "tham quan kiến tập",
    "img": "見学します.jpg",
    "furigana": "<ruby><rb>見学</rb><rp>(</rp><rt>けんがく</rt><rp>)</rp></ruby>します",
    "en": "inspection, study by observation, field trip",
    "masu": "けんがくします"
  },
  {
    "no": 7,
    "group": "III",
    "is": false,
    "kanji": "研究します",
    "kanji2": "",
    "note": "",
    "vi": "nghiên cứu",
    "img": "研究します.jpg",
    "furigana": "<ruby><rb>研究</rb><rp>(</rp><rt>けんきゅう</rt><rp>)</rp></ruby>します",
    "en": "study, research, investigation",
    "masu": "けんきゅうします"
  },
  {
    "no": 8,
    "group": "III",
    "is": false,
    "kanji": "コピーします",
    "kanji2": "",
    "note": "",
    "vi": "copy , phô - tô",
    "img": "コピーします.jpg",
    "furigana": "こぴーします",
    "en": "copy, photocopy, blurb on a book jacket, catch copy",
    "masu": "こぴーします"
  },
  {
    "no": 9,
    "group": "III",
    "is": false,
    "kanji": "散歩します",
    "kanji2": "",
    "note": "こうえんを~",
    "vi": "đi dạo [ ở công viên ]",
    "img": "こうえんを散歩します.jpg",
    "furigana": "<ruby><rb>散歩</rb><rp>(</rp><rt>さんぽ</rt><rp>)</rp></ruby>します",
    "en": "walk, stroll",
    "masu": "さんぽします"
  },
  {
    "no": 10,
    "group": "III",
    "is": false,
    "kanji": "残業します",
    "kanji2": "",
    "note": "",
    "vi": "làm thêm giờ",
    "img": "残業します.jpg",
    "furigana": "<ruby><rb>残業</rb><rp>(</rp><rt>ざんぎょう</rt><rp>)</rp></ruby>します",
    "en": "overtime (work)",
    "masu": "ざんぎょうします"
  },
  {
    "no": 11,
    "group": "III",
    "is": false,
    "kanji": "します",
    "kanji2": "",
    "note": "",
    "vi": "làm , chơi",
    "img": "します.jpg",
    "furigana": "します",
    "en": "to do, to cause to become, to make (into), to turn (into), to serve as, to act as, to work as, to wear (clothes, a facial expression, etc.), to judge as being, to view as being, to think of as, to treat as, to use as, to decide on, to choose, to be sensed (of a smell, noise, etc.), to be (in a state...",
    "masu": "します"
  },
  {
    "no": 12,
    "group": "III",
    "is": false,
    "kanji": "します",
    "kanji2": "",
    "note": "ネクタイを~",
    "vi": "đeo [ cà vạt ]",
    "img": "ネクタイをします.jpg",
    "furigana": "します",
    "en": "to do, to cause to become, to make (into), to turn (into), to serve as, to act as, to work as, to wear (clothes, a facial expression, etc.), to judge as being, to view as being, to think of as, to treat as, to use as, to decide on, to choose, to be sensed (of a smell, noise, etc.), to be (in a state...",
    "masu": "します"
  },
  {
    "no": 13,
    "group": "III",
    "is": false,
    "kanji": "修理します",
    "kanji2": "",
    "note": "",
    "vi": "sửa chữa , tu sửa",
    "img": "修理します.jpg",
    "furigana": "<ruby><rb>修理</rb><rp>(</rp><rt>しゅうり</rt><rp>)</rp></ruby>します",
    "en": "repairing, mending, servicing",
    "masu": "しゅうりします"
  },
  {
    "no": 14,
    "group": "III",
    "is": false,
    "kanji": "出張します",
    "kanji2": "",
    "note": "",
    "vi": "đi công tác",
    "img": "出張します.jpg",
    "furigana": "<ruby><rb>出張</rb><rp>(</rp><rt>しゅっちょう</rt><rp>)</rp></ruby>します",
    "en": "official tour, business trip",
    "masu": "しゅっちょうします"
  },
  {
    "no": 15,
    "group": "III",
    "is": false,
    "kanji": "紹介します",
    "kanji2": "",
    "note": "",
    "vi": "giới thiệu",
    "img": "紹介します.jpg",
    "furigana": "<ruby><rb>紹介</rb><rp>(</rp><rt>しょうかい</rt><rp>)</rp></ruby>します",
    "en": "introduction, presentation, referral, listing",
    "masu": "しょうかいします"
  },
  {
    "no": 16,
    "group": "III",
    "is": false,
    "kanji": "食事します",
    "kanji2": "",
    "note": "",
    "vi": "ăn cơm , dùng bữa",
    "img": "食事します.jpg",
    "furigana": "<ruby><rb>食事</rb><rp>(</rp><rt>しょくじ</rt><rp>)</rp></ruby>します",
    "en": "meal, to eat",
    "masu": "しょくじします"
  },
  {
    "no": 17,
    "group": "III",
    "is": false,
    "kanji": "心配します",
    "kanji2": "",
    "note": "",
    "vi": "lo lắng",
    "img": "心配します.jpg",
    "furigana": "<ruby><rb>心配</rb><rp>(</rp><rt>しんぱい</rt><rp>)</rp></ruby>します",
    "en": "worry, concern, anxiety, care, help, aid, assistance",
    "masu": "しんぱいします"
  },
  {
    "no": 18,
    "group": "III",
    "is": false,
    "kanji": "説明します",
    "kanji2": "",
    "note": "",
    "vi": "giải thích , trình bày",
    "img": "説明します.jpg",
    "furigana": "<ruby><rb>説明</rb><rp>(</rp><rt>せつめい</rt><rp>)</rp></ruby>します",
    "en": "explanation, exposition",
    "masu": "せつめいします"
  },
  {
    "no": 19,
    "group": "III",
    "is": false,
    "kanji": "洗濯します",
    "kanji2": "",
    "note": "",
    "vi": "giặt ( áo quần )",
    "img": "洗濯します.jpg",
    "furigana": "<ruby><rb>洗濯</rb><rp>(</rp><rt>せんたく</rt><rp>)</rp></ruby>します",
    "en": "washing, laundry",
    "masu": "せんたくします"
  },
  {
    "no": 20,
    "group": "III",
    "is": false,
    "kanji": "掃除します",
    "kanji2": "",
    "note": "",
    "vi": "dọn vệ sinh ( căn phòng )",
    "img": "掃除します.jpg",
    "furigana": "<ruby><rb>掃除</rb><rp>(</rp><rt>そうじ</rt><rp>)</rp></ruby>します",
    "en": "cleaning, sweeping, dusting, scrubbing",
    "masu": "そうじします"
  },
  {
    "no": 21,
    "group": "III",
    "is": true,
    "kanji": "連れて来ます",
    "kanji2": "",
    "note": "",
    "vi": "dẫn ( một ai đó ) đến",
    "img": "連れて来ます.jpg",
    "furigana": "<ruby><rb>連</rb><rp>(</rp><rt>つ</rt><rp>)</rp></ruby>れて<ruby><rb>来</rb><rp>(</rp><rt>き</rt><rp>)</rp></ruby>ます",
    "en": "to lead, to take (a person)",
    "masu": "つれてきます"
  },
  {
    "no": 22,
    "group": "III",
    "is": false,
    "kanji": "電話します",
    "kanji2": "",
    "note": "",
    "vi": "gọi điện thoại",
    "img": "電話します.jpg",
    "furigana": "<ruby><rb>電話</rb><rp>(</rp><rt>でんわ</rt><rp>)</rp></ruby>します",
    "en": "telephone call, phone call, telephone (device), phone",
    "masu": "でんわします"
  },
  {
    "no": 23,
    "group": "III",
    "is": false,
    "kanji": "勉強します",
    "kanji2": "",
    "note": "",
    "vi": "học",
    "img": "勉強します.jpg",
    "furigana": "<ruby><rb>勉強</rb><rp>(</rp><rt>べんきょう</rt><rp>)</rp></ruby>します",
    "en": "study, diligence, discount, reduction",
    "masu": "べんきょうします"
  },
  {
    "no": 24,
    "group": "III",
    "is": true,
    "kanji": "持って来ます",
    "kanji2": "",
    "note": "",
    "vi": "mang đến",
    "img": "持って来ます.jpg",
    "furigana": "<ruby><rb>持</rb><rp>(</rp><rt>も</rt><rp>)</rp></ruby>って<ruby><rb>来</rb><rp>(</rp><rt>き</rt><rp>)</rp></ruby>ます",
    "en": "to hold (in one's hand), to take, to carry, to possess, to have, to own, to maintain, to keep, to last, to be durable, to keep, to survive, to take charge of, to be in charge of",
    "masu": "もってきます"
  },
  {
    "no": 25,
    "group": "III",
    "is": false,
    "kanji": "予約します",
    "kanji2": "",
    "note": "",
    "vi": "đặt chỗ , đặt trước",
    "img": "予約します.jpg",
    "furigana": "<ruby><rb>予約</rb><rp>(</rp><rt>よやく</rt><rp>)</rp></ruby>します",
    "en": "reservation, appointment, booking, advance order, contract, subscription, pledge",
    "masu": "よやくします"
  },
  {
    "no": 26,
    "group": "III",
    "is": false,
    "kanji": "留学します",
    "kanji2": "",
    "note": "",
    "vi": "du học",
    "img": "留学します.jpg",
    "furigana": "<ruby><rb>留学</rb><rp>(</rp><rt>りゅうがく</rt><rp>)</rp></ruby>します",
    "en": "studying abroad (usu. at university level)",
    "masu": "りゅうがくします"
  }
]